## Python Basics -Programming Assignment 8

1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np 

def matadd(mat1, mat2) :
    mat3 = mat1+mat2
    return mat3


mat1 = np.array([[2,4], [5,6]])
mat2 = np.array([[5,6], [8,9]])

print(f'Adding two matrix {mat1}\n  and matrix {mat2} : \n{matadd(mat1, mat2)}')
        
        

Adding two matrix [[2 4]
 [5 6]]
  and matrix [[5 6]
 [8 9]] : 
[[ 7 10]
 [13 15]]


2. Write a Python Program to Multiply Two Matrices?

In [2]:
def matmult(mat1, mat2) :
    mat3 = mat1@mat2
    return mat3


mat1 = np.array([[2,4], [5,6]])
mat2 = np.array([[5,6], [8,9]])

print(f'Multiplication of two matrix {mat1}\n  and matrix {mat2} : \n{matmult(mat1, mat2)}')
        

Multiplication of two matrix [[2 4]
 [5 6]]
  and matrix [[5 6]
 [8 9]] : 
[[42 48]
 [73 84]]


3. Write a Python Program to Transpose a Matrix?

In [3]:
def matT(mat1) :
    mat2 = mat1.T
    return mat2

mat1 = np.array([[2,4], [5,6]])

print(f'Transpose of matrix {mat1} : \n{matT(mat1)}')
        

Transpose of matrix [[2 4]
 [5 6]] : 
[[2 5]
 [4 6]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
#let us take the words input as list. 

def word_sort(listwords) :
    list1 = sorted(listwords)
    return list1



wordlist = ['world', 'bag', 'onion', 'pug', 'mango', 'fun']

print(f'Output after sorting words in alphabetic order : {word_sort(wordlist)}')

Output after sorting words in alphabetic order : ['bag', 'fun', 'mango', 'onion', 'pug', 'world']


5. Write a Python Program to Remove Punctuation From a String?

In [5]:
from string import punctuation

def remove_punc(instring, punclist) : 
    
    inlist = [i for i in instring]

    for ele in instring: 
        if ele in punclist : 
            inlist.remove(ele)

    list2 = ''.join(inlist)
    return list2




punclist = [i for i in punctuation]
#print(punclist)

instring = 'Hi! How are you ? -- I am fine thank you. '
 
print(f'Input string : {instring}')    
print(f'Removing the punctuation from the input string:\n {remove_punc(instring, punclist)}')     





Input string : Hi! How are you ? -- I am fine thank you. 
Removing the punctuation from the input string:
 Hi How are you   I am fine thank you 
